set = set()
a=str(input("Enter your number:"))
set.add(a)
b=str(input("Enter your number:"))
set.add(b)
c=str(input("Enter your number:"))
set.add(c)
d=str(input("Enter your number:"))
set.add(d)
e=str(input("Enter your number:"))
set.add(e)
f=str(input("Enter your number:"))
set.add(f)
g=str(input("Enter your number:"))
set.add(g)
h=str(input("Enter your number:"))
set.add(h)
print(set)
