Marks=[]
f1=int(input("Enter Marks "))
Marks.append(f1)
f2=int(input("Enter Marks "))
Marks.append(f2)
f3=int(input("Enter Marks "))
Marks.append(f3)
f4=int(input("Enter Marks "))
Marks.append(f4)
f5=int(input("Enter Marks "))
Marks.append(f5)
Marks.sort()
print(Marks)